// Courses
export const LIST_COURSES_REQUEST = 'LIST_COURSES_REQUEST';
export const LIST_COURSES_RESPONSE = 'LIST_COURSES_RESPONSE';

export const SAVE_COURSE_REQUEST = 'SAVE_COURSE_REQUEST';
export const SAVE_COURSE_RESPONSE = 'SAVE_COURSE_RESPONSE';

export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST';
export const UPDATE_COURSE_RESPONSE = 'UPDATE_COURSE_RESPONSE';

//Author
