// Courses
export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_RESPONSE = 'GET_COURSES_RESPONSE';

//Author
export const GET_AUTHORS_REQUEST = 'GET_AUTHORS_REQUEST';
export const GET_AUTHORS_RESPONSE = 'GET_AUTHORS_RESPONSE';
